<a href="https://colab.research.google.com/github/marisukanis/Repository1/blob/main/01_Overview_of_TensorFlow_and_Machine_Learning_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow 2.0 <a class="tocSkip">





In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3]).reshape(-1,1)
print(a.shape)
b = np.array([1,2])
print(b.shape)

(3, 1)
(2,)


In [10]:
a+b

array([[2, 3],
       [3, 4],
       [4, 5]])

In [11]:
import tensorflow as tf
print('Version TensorFlow :',tf.__version__)
import numpy as np
print('Version Numpy :',np.__version__)
import sys
print('Interpreter Pythona and version:',sys.version)

Version TensorFlow : 2.9.2
Version Numpy : 1.21.6
Interpreter Pythona and version: 3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]


# Hello TensorFlow 

In [12]:
hello = tf.constant('Hello in Tensorflow project!!')
tf.print(hello)

Hello in Tensorflow project!!


# Pernament

In [ ]:
const1 = tf.constant(34, name='x')
const2 = tf.constant(59.0, name='y')
const3 = tf.constant(32.0, dtype=tf.float32, name='z')
print('const1 (x): ', const1)
print('const2 (y): ', const2)
print('const3 (z): ', const3)

const1 (x):  tf.Tensor(34, shape=(), dtype=int32)
const2 (y):  tf.Tensor(59.0, shape=(), dtype=float32)
const3 (z):  tf.Tensor(32.0, shape=(), dtype=float32)


In [ ]:
print('run([const1,const2,const3]) : ', end='')
tf.print([const1, const2, const3])

run([const1,const2,const3]) : [34, 59, 32]


# Operations

In [ ]:
op1 = tf.add(const2, const3)
op2 = tf.multiply(const2, const3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  tf.Tensor(91.0, shape=(), dtype=float32)
op2 :  tf.Tensor(1888.0, shape=(), dtype=float32)


In [ ]:
print('run(op1) : ', end='')
tf.print(op1)
print('run(op2) : ', end='')
tf.print(op2)

run(op1) : 91
run(op2) : 1888


# Functions

In [ ]:
@tf.function
def add_func(x):
    y = x + 10
    return y

In [ ]:
x = tf.constant([10, 20, 30, 40])

In [ ]:
result = add_func(x)

In [ ]:
print(result)

tf.Tensor([20 30 40 50], shape=(4,), dtype=int32)


In [ ]:
tf.print(result)

[20 30 40 50]


# Create tensors from existing objects

## Tensors of zero order (scalars)

In [ ]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : ', end='')
tf.print(tf_t)

tf_t :  tf.Tensor(5.0, shape=(), dtype=float64)
run(tf_t) : 5


## 1st order tensors (vectors)

In [ ]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print('Shape a1dim : ', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : ')
tf.print(tf_t)

Shape a1dim :  (5,)
tf_t :  tf.Tensor([1.   2.   3.   4.   5.99], shape=(5,), dtype=float64)
tf_t[0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[0] :  tf.Tensor(3.0, shape=(), dtype=float64)
run(tf_t) : 
[1 2 3 4 5.99]


## 2nd order tensors (matrices)

In [ ]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print('Shape a2dim : ', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) :') 
tf.print(tf_t)

Shape a2dim :  (3, 5)
tf_t :  tf.Tensor(
[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]], shape=(3, 5), dtype=float64)
tf_t[0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][2] :  tf.Tensor(4.0, shape=(), dtype=float64)
run(tf_t) :
[[1 2 3 4 5.99]
 [2 3 4 5 6.99]
 [3 4 5 6 7.99]]


## 3rd order tensors

In [ ]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('Shape a3dim : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : ')
tf.print(tf_t)

Shape a3dim :  (2, 2, 2)
tf_t :  tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][1][1] :  tf.Tensor(8.0, shape=(), dtype=float64)
run(tf_t) : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Variables

In [ ]:
# Placeholdery are not executable immediately, so we need to disable execution requests in TF2
tf.compat.v1.disable_eager_execution()

# Linear model y = w * x + b
# Defining model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Defining model input and output
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b

print('w:', w)
print('x:', x)
print('b:', b)
print('y:', y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32>
x: Tensor("Placeholder:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32>
y: Tensor("add:0", dtype=float32)


In [ ]:
# Session initiation and printing of the y variable
with tf.compat.v1.Session() as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  print('run(y,{x:[1,2,3,4]}) : ', sess.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


# Create tensors from library functions

In [ ]:
a = tf.zeros((100,))
print(a)

Tensor("zeros:0", shape=(100,), dtype=float32)


In [ ]:
b = tf.ones((100,))
print(b)

Tensor("ones:0", shape=(100,), dtype=float32)


In [ ]:
c = tf.fill((100,), 5)
print(c)

Tensor("Fill:0", shape=(100,), dtype=int32)


# Computational graphs

## Building and running a simple computational graph

In [ ]:
# Placeholders are not executable immediately, so we need to disable execution requests in TF2
tf.compat.v1.disable_eager_execution()

# Linear model y = w * x + b
# Defining model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Defining model input and output
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.compat.v1.Session() as sess:
    # Initialization and printing of the y variable
    tf.compat.v1.global_variables_initializer().run()
    output = sess.run(y, {x: [1, 2, 3, 4]})
print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


## Graph on computing devices

### List of available devices

In [ ]:
#On Collab beforehand, change the hardware acceleration to GPU
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15879697661676224077
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14444920832
locality {
  bus_id: 1
  links {
  }
}
incarnation: 9394181085866978986
physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
xla_global_id: 416903419
]


### Default deployment

In [ ]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Defining model input and output
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b

config = tf.compat.v1.ConfigProto()
config.log_device_placement = True

with tf.compat.v1.Session(config=config) as sess:
    # initialization and printing of the y variable
    sess.run(tf.compat.v1.global_variables_initializer())
    print('input', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


### Deployment on the CPU

In [ ]:
ops.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Defining model parameters
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Defining model input and output
    x = tf.compat.v1.placeholder(tf.float32)
    y = w * x + b

    config = tf.compat.v1.ConfigProto()
    config.log_device_placement = True

    with tf.compat.v1.Session(config=config) as sess:
        # initialization and printing of the y variable
        sess.run(tf.compat.v1.global_variables_initializer())
        print('output', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


### Deployment to CPU and GPU

In [ ]:
ops.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Defining model parameters
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Defining model input and output
    x = tf.compat.v1.placeholder(tf.float32)
with tf.device('/device:GPU:0'):
    y = w * x + b

config = tf.compat.v1.ConfigProto()
config.log_device_placement = True

with tf.compat.v1.Session(config=config) as sess:
    # initialization and printing of the y variable
    sess.run(tf.compat.v1.global_variables_initializer())
    print('output', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


## Making graph g the default

In [ ]:
g = tf.Graph()
output = 0

# Przyjmujemy model liniowy y = w * x + b

with g.as_default():
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.compat.v1.placeholder(tf.float32)
    y = w * x + b

with tf.compat.v1.Session(graph=g) as sess:
    # Inicjacja i wydruk zmiennej y
    tf.compat.v1.global_variables_initializer().run()
    output = sess.run(y, {x: [1, 2, 3, 4]})

print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


# Logistic regression with TensorFlow

### NOTE: Necessary to restart the environment due to the use of eager mode disabled earlier!

## Data preparing 

In [ ]:
import tensorflow as tf
from keras.datasets import mnist
import numpy as np

# Preparing x and y data

(x_train,y_train), (x_test,y_test)=mnist.load_data()

print('Loaded x and y')
print('Training: x:{}, y:{}'.format(len(x_train),y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))

Wczytane x i y
Szkolenie: x:60000, y:(60000,)
Test: x:(10000, 28, 28), y:(10000,)


In [ ]:
# Loading data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Conversion to float32
x_train, x_test = np.array(x_train, np.float32), np.array(x_test, np.float32)

# Flatten the images to a one-dimensional vector of 784 pixels (28x28).
x_train, x_test = x_train.reshape([-1, 784]), x_test.reshape([-1, 784])

# Normalize values from [0, 255] to [0, 1].
x_train, x_test = x_train / 255., x_test / 255.


## Dividing data into batches

In [ ]:
# MNIST parameters

num_classes = 10 # 0 to 9 digits

num_features = 784 # 28*28

# Training parameters

learning_rate = 0.01

training_steps = 1000

batch_size = 256

display_step = 5

In [ ]:
train_data=tf.data.Dataset.from_tensor_slices((x_train,y_train))

train_data=train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)

## Model building

In [ ]:
# Weights with size [784, 10].
W = tf.Variable(tf.ones([num_features, num_classes]), tf.float32, name="weight")

# Bias with size [10].

b = tf.Variable(tf.zeros([num_classes]), tf.float32, name="bias")

## Loss function and logistic regression

In [ ]:
def cross_entropy(y_pred, y_true):
    # Encoding labels
    y_true = tf.one_hot(y_true, depth=num_classes)
    
    # In order to avoid zero values, we replace small values with 1
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)
    
    # Counting entropy 
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred),1))


def logistic_regression(x):

    # We will use softmax to normalize the results to a probability distribution.
    return tf.nn.softmax(tf.matmul(x, W) + b)

## Accuracy function and optimizer

In [ ]:
def accuracy(y_pred, y_true):

  # The prediction class is the index of the highest score in the prediction vector (i.e. argmax)

  correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))

  return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# SGD Optimizer

optimizer = tf.optimizers.SGD(learning_rate)

## Model Training 

In [ ]:
# Optymalization process

def run_optimization(x, y):

    with tf.GradientTape() as g:
        
        pred = logistic_regression(x)
        
        loss = cross_entropy(pred, y)

    # Gradients counting 

    gradients = g.gradient(loss, [W, b])

    # Update weights and biases

    optimizer.apply_gradients(zip(gradients, [W, b]))

In [ ]:
# Start training for a given number of epochs

for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):

    run_optimization(batch_x, batch_y)

    #Calculation of parameters for each era

    if step % display_step == 0:

        pred = logistic_regression(batch_x)

        loss = cross_entropy(pred, batch_y)

        acc = accuracy(pred, batch_y)

        print("step: %i, loss: %f, accuracy: %f" % (step, loss, acc))

step: 5, loss: 2.243814, accuracy: 0.644531
step: 10, loss: 2.193093, accuracy: 0.644531
step: 15, loss: 2.137759, accuracy: 0.710938
step: 20, loss: 2.107600, accuracy: 0.671875
step: 25, loss: 2.031835, accuracy: 0.765625
step: 30, loss: 1.993534, accuracy: 0.750000
step: 35, loss: 1.982471, accuracy: 0.695312
step: 40, loss: 1.928905, accuracy: 0.734375
step: 45, loss: 1.860248, accuracy: 0.761719
step: 50, loss: 1.873184, accuracy: 0.710938
step: 55, loss: 1.825601, accuracy: 0.765625
step: 60, loss: 1.799773, accuracy: 0.734375
step: 65, loss: 1.765999, accuracy: 0.773438
step: 70, loss: 1.700775, accuracy: 0.757812
step: 75, loss: 1.715378, accuracy: 0.753906
step: 80, loss: 1.687870, accuracy: 0.761719
step: 85, loss: 1.654011, accuracy: 0.761719
step: 90, loss: 1.584464, accuracy: 0.796875
step: 95, loss: 1.610246, accuracy: 0.750000
step: 100, loss: 1.558839, accuracy: 0.750000
step: 105, loss: 1.519194, accuracy: 0.800781
step: 110, loss: 1.553070, accuracy: 0.773438
step: 11

In [ ]:
# Model testing
pred = logistic_regression(x_test)

print("Test Accuracy: %f" % accuracy(pred, y_test))

Test Accuracy: 0.869700


# Logistic regression with Keras

In [ ]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()

mnist.y_onehot = True

x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.7743 - accuracy: 0.8169
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4569 - accuracy: 0.8804
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4039 - accuracy: 0.8909
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3773 - accuracy: 0.8971
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.3355 - accuracy: 0.9085


[0.33554795384407043, 0.9085000157356262]